### ISSUE TITLE
Fresh installation: error 

### ISSUE THREAD

**Issue by jquinter** [MarcusCemes/image-processing-pipeline#20]
**Describe the bug**
Just installed, tested with input/output folder, error appears:

```
➜  form git:(master) ✗ ipp -i src/assets/imgs -o src/assets/imgs/ipp/

        ._______________________
        |   \______   \______   \
        |   ||     ___/|     ___/
        |   ||    |    |    |
        |___||____|    |____|


        Image Processing Pipeline
          https://git.io/JJZdv

(node:32909) UnhandledPromiseRejectionWarning: TypeError: common_1.interpolateTemplates is not a function
    at /usr/local/lib/node_modules/@ipp/cli/dist/operators/save.js:36:51
    at /usr/local/lib/node_modules/@ipp/cli/dist/lib/stream/operators/map_parallel.js:32:42
    at /usr/local/lib/node_modules/@ipp/cli/dist/lib/stream/operators/map_parallel.js:43:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:32909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32909) UnhandledPromiseRejectionWarning: TypeError: common_1.interpolateTemplates is not a function
    at /usr/local/lib/node_modules/@ipp/cli/dist/operators/save.js:36:51
    at /usr/local/lib/node_modules/@ipp/cli/dist/lib/stream/operators/map_parallel.js:32:42
    at /usr/local/lib/node_modules/@ipp/cli/dist/lib/stream/operators/map_parallel.js:43:19
(node:32909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
            Version: 1.2.0
            Concurrency: 20
            Manifest: enabled
            Clean: disabled

              Total: 2
              Completed: 2

              ⠦ Processing
```
I must add: the processing step stuck for several minutes, until I decided to report this bug (and interrupted the execution)

**Steps to reproduce**
Steps to reproduce the behaviour:

1. npm i -g @ipp/cli
2. ipp -i [some input folder] -o [some output folder]
3. See error

**Expected behaviour**
I would love to see a simple starting example working.

**Screenshots**
![image](https://user-images.githubusercontent.com/1566934/95683077-71276b80-0bbf-11eb-848c-3448e984e9dd.png)

![image](https://user-images.githubusercontent.com/1566934/95683041-24439500-0bbf-11eb-836b-a42b876f6fe7.png)

![image](https://user-images.githubusercontent.com/1566934/95683059-4fc67f80-0bbf-11eb-9749-1a5bceda7e3e.png)

**System information:**

- OS: macOS 10.15.7
- Node version: 14.2.0
- IPP version: 1.2.0

**Additional context**
I just installed, and tried with an input folder.

**Comment by MarcusCemes** [comment]
This should be resolved in version `1.2.1` of the CLI 🎉
